### ISSUE TITLE
Error found: --tracker_type is deep_sort

### ISSUE THREAD

**Issue by faisalshahbaz** [world4jason/tracking_by_detection_with_yolo_deep_sort#1]
Hello,
I am very thankful for repo. 
I got an error, when i using  --tracker_type is deep_sort.
`parser.add_argument('--tracker_type', required=False, default="deep_sort")
`
Error found: 
```
/home/mikaels/Documents/EnvTrackingClasses/lib/python3.6/site-packages/sklearn/utils/linear_assignment_.py:21: DeprecationWarning: The linear_assignment_ module is deprecated in 0.21 and will be removed from 0.23. Use scipy.optimize.linear_sum_assignment instead.
  DeprecationWarning)
Traceback (most recent call last):
  File "/home/mikaels/Documents/EnvTrackingClasses/tracking_by_detection_with_yolo_deep_sort/demo.py", line 116, in <module>
    main(parser.parse_args())
  File "/home/mikaels/Documents/EnvTrackingClasses/tracking_by_detection_with_yolo_deep_sort/demo.py", line 58, in main
    args.split)
  File "/home/mikaels/Documents/EnvTrackingClasses/tracking_by_detection_with_yolo_deep_sort/multi_tracker.py", line 116, in gen_feature
    crop_features[index] = self.encoder(image, np.array(g_boxes[index]).copy())
TypeError: 'NoneType' object is not callable

```

**Comment by faisalshahbaz** [comment]
hi @world4jason

**Comment by Ashwin-Ramesh2607** [comment]
Hey,
The problem was that the deep_sort model path (mars-small128.pb file) was not initialized to the deep_sort_model_path variable. This was why it was giving a NoneType error. Just setting the variable fixes the error.

Line number 37 in demo.py

`    mot = Multi_tracker(
        max_cosine_distance=args.max_cosine_distance,
        nn_budget=args.nn_budget,
        tracker_type=args.tracker_type,
        nms_threshold=args.tracker_nms_threshold,
        deep_sort_model_path=args.sort_model_path,
        labels=labels
    )`

**Comment by faisalshahbaz** [comment]
@Ashwin-Ramesh2607 
thank you bro.

**Comment by world4jason** [comment]
@Ashwin-Ramesh2607 thanks a lot.
@faisalshahbaz sorry i'm doing my compulsory military service now, so i cant reply immediately
